"""
Send an EOD report via MS Graph email.

Configuration (via .env):
    AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_CLIENT_SECRET  — MS Graph auth
    EOD_REPORT_EMAIL  — default recipient when none provided explicitly
"""

import logging
import os
from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from backend.work_tracker.eod_report_generator import EODReport

logger = logging.getLogger(__name__)

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {{ font-family: sans-serif; max-width: 800px; margin: 2em auto; color: #222; }}
    h1 {{ color: #0066cc; }}
    h2 {{ color: #444; border-bottom: 1px solid #ccc; padding-bottom: 4px; }}
    table {{ border-collapse: collapse; width: 100%; }}
    th, td {{ text-align: left; padding: 6px 10px; border-bottom: 1px solid #eee; }}
    th {{ background: #f0f4f8; }}
    .meta {{ color: #666; font-size: 0.9em; }}
    .total {{ font-weight: bold; }}
    .adj {{ color: #888; font-size: 0.85em; }}
    ul {{ margin: 0 0 0.5em 1.5em; padding: 0; }}
    li {{ margin: 2px 0; }}
  </style>
</head>
<body>
  <h1>DevTrack EOD Report — {report_date}</h1>
  <p class="meta">Total time logged: <strong>{total_str}</strong></p>

  <h2>Sessions</h2>
  <table>
    <thead>
      <tr><th>Ticket / Ref</th><th>Time</th><th>Commits</th><th>Notes</th></tr>
    </thead>
    <tbody>
      {sessions_rows}
    </tbody>
    <tfoot>
      <tr class="total"><td colspan="3">Total</td><td>{total_str}</td></tr>
    </tfoot>
  </table>

  {narrative_section}

  {achievements_section}

  {pending_section}

  <hr>
  <p class="meta">Generated by <a href="https://github.com/sraj0501/automation_tools">DevTrack</a></p>
</body>
</html>
"""


def _build_html(report: "EODReport") -> str:
    rows = []
    for s in report.sessions:
        h, m = divmod(s.duration_minutes, 60)
        dur = f"{h}h {m}m" if h else f"{m}m"
        adj_note = ' <span class="adj">[adjusted]</span>' if s.adjusted else ""
        ticket = s.ticket_ref or "<em>(general)</em>"
        commits_count = len(s.commits)
        commits_cell = str(commits_count) if commits_count else "—"
        desc = s.description or "—"
        rows.append(
            f"<tr><td>{ticket}</td><td>{dur}{adj_note}</td>"
            f"<td>{commits_cell}</td><td>{desc}</td></tr>"
        )
    sessions_rows = "\n      ".join(rows) if rows else "<tr><td colspan='4'>No sessions recorded.</td></tr>"

    narrative_section = ""
    if report.ai_narrative:
        narrative_section = f"<h2>Day Summary</h2><p>{report.ai_narrative}</p>"

    achievements_section = ""
    if report.achievements:
        items = "".join(f"<li>✅ {a}</li>" for a in report.achievements)
        achievements_section = f"<h2>Achievements</h2><ul>{items}</ul>"

    pending_items = list(report.in_progress) + list(report.pending_tomorrow)
    pending_section = ""
    if pending_items:
        items = "".join(f"<li>⏳ {p}</li>" for p in pending_items)
        pending_section = f"<h2>Pending / In Progress</h2><ul>{items}</ul>"

    return _HTML_TEMPLATE.format(
        report_date=report.date,
        total_str=report.total_str(),
        sessions_rows=sessions_rows,
        narrative_section=narrative_section,
        achievements_section=achievements_section,
        pending_section=pending_section,
    )


class EODEmailer:
    """Send EOD reports via MS Graph email."""

    async def send(self, report: "EODReport", recipient: Optional[str] = None) -> bool:
        """Email the EOD report.

        Args:
            report:    Populated EODReport.
            recipient: Override recipient; falls back to EOD_REPORT_EMAIL env var.

        Returns True on success, False on failure (non-fatal).
        """
        to = recipient or os.getenv("EOD_REPORT_EMAIL", "")
        if not to:
            logger.warning("EODEmailer: no recipient — set EOD_REPORT_EMAIL or pass --email")
            return False

        subject = f"[DevTrack] EOD Report — {report.date} ({report.total_str()})"
        html_body = _build_html(report)
        return await self._send_via_graph(subject, html_body, to)

    async def _send_via_graph(self, subject: str, html_body: str, recipient: str) -> bool:
        try:
            import configparser as cp
            parser = cp.ConfigParser()
            parser["graph"] = {
                "clientId": os.getenv("AZURE_CLIENT_ID", ""),
                "tenantId": os.getenv("AZURE_TENANT_ID", ""),
                "clientSecret": os.getenv("AZURE_CLIENT_SECRET", ""),
                "graphUserScopes": "Mail.Send",
            }
            section = parser["graph"]

            from backend.msgraph_python.graph import Graph
            graph = Graph(section)
            await graph.send_mail(subject=subject, body=html_body, recipient=recipient)
            logger.info(f"EOD report emailed to {recipient}")
            return True
        except Exception as e:
            logger.warning(f"EODEmailer: graph send failed: {e}")
            return False
